---
version: '2.1'
services:

  zookeeper:
    container_name: zookeeper
    hostname: zookeeeper
    image: confluentinc/cp-zookeeper:4.0.0-3
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      zk_id: "1"
    extra_hosts:
      - "moby:127.0.0.1"
      - "localhost: 127.0.0.1"
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:2181"]
#      interval: 10s
#      timeout: 10s
#      retries: 5

  kafka:
    container_name: kafka
    hostname: kafka
    image: confluentinc/cp-kafka:4.0.0-3
#    depends_on:
#      zookeeper:
#        condition: service_healthyå
    links:
      - zookeeper
    ports:
      - "0.0.0.0:9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ADVERTISED_HOST: "localhost"
    extra_hosts:
      - "moby:127.0.0.1"
      - "localhost: 127.0.0.1"
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:9092"]
#      interval: 10s
#      timeout: 10s
#      retries: 5

  kafka-connect:
    container_name: kafka-connect
    image: maxsakharov/kafka-connect-rest
    hostname: kafka-connect
#    depends_on:
#      kafka:
#        condition: service_healthy
    links:
      - zookeeper
      - kafka
    ports:
      - "0.0.0.0:8083:8083"
      - "0.0.0.0:9200:9200"
    volumes:
      - ./docker-generated/tmp:/tmp
      - ./docker-generated/var/log/kafka:/var/log/kafka:rw
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONNECT_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONNECT_REST_PORT: 8083
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_GROUP_ID: kafka-connect-test
      CONNECT_CONFIG_STORAGE_TOPIC: kafka.connect.test.storage.config
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: kafka.connect.test.storage.offset
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: kafka.connect.test.storage.status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: 'false'
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_PLUGIN_PATH: /usr/share/java,/etc/kafka-connect/jars
    extra_hosts:
      - "moby:127.0.0.1"
      - "localhost: 127.0.0.1"
